name: food_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.22.0
  smooth_star_rating: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
 